//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsage
    {
        public int UsageID { get; set; }
        public int StageID { get; set; }
        public int EquipmentID { get; set; }
        public System.DateTime UsageDate { get; set; }
        public double HoursUsed { get; set; }
        public int OrdersID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
