//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServices
    {
        public int OrderServiceID { get; set; }
        public int OrderID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime ServiceDate { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
