//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSubcontractors
    {
        public int ProjectSubID { get; set; }
        public int StageID { get; set; }
        public int SubcontractorID { get; set; }
        public System.DateTime AssignmentDate { get; set; }
        public string TaskDescription { get; set; }
    
        public virtual ProjectStages ProjectStages { get; set; }
        public virtual Subcontractors Subcontractors { get; set; }
    }
}
