//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControl
    {
        public int QCID { get; set; }
        public int StageID { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public string Inspector { get; set; }
        public string Result { get; set; }
        public string Notes { get; set; }
    
        public virtual ProjectStages ProjectStages { get; set; }
    }
}
